name: Run Pytest and Generate Report

permissions:
  contents: write
  pages: write

on:
  push:
    branches: [ "master" ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            echo "No requirements.txt, continuing..."
          fi
          pip install pytest allure-pytest requests pyyaml

      - name: Run Pytest
        run: |
          pytest -v -s --alluredir=report/allure-results

      - name: Generate Allure Report
        uses: simple-elf/allure-report-action@v1.7
        with:
          allure_results: report/allure-results
          allure_report: report/allure-report
          keep_reports: 5

      - name: Deploy Allure Report to GitHub Pages
        if: success() && always()  # run deploy only after tests finished (adjust as needed)
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: report/allure-report
          publish_branch: gh-pages